    
branches:
  only:
  - master
language: bash

branches:
  only:
  - master
language: bash

before_install: 
- wget https://github.com/jgm/pandoc/releases/download/2.1.1/pandoc-2.1.1-1-amd64.deb
  && ar p pandoc-2.1.1-1-amd64.deb data.tar.xz | tar xJ
- sudo apt-get update -qq
- sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra
  texlive-fonts-recommended texlive-fonts-extra  texlive-science
- sudo apt-get install lmodern
- chmod +x push.sh
script:
- make pdf

after_success:
- "./push.sh"
